import React, { useEffect, useState } from 'react';
import { ArrowRight, Bike, Dumbbell, Facebook, Globe2, Instagram, Leaf, Mail, MapPin, Menu, PackageCheck, Phone, ShieldCheck, Truck, X, CheckCircle2 } from 'lucide-react';
import { copy } from './storefront-copy';
import { ecommerce, trackEvent, trackOrderResult, installClickTracking } from './analytics.js';
import '@fontsource-variable/inter';
import '@fontsource-variable/noto-sans-arabic';
import '@fontsource/libre-baskerville/700.css';
const images=['creatine','citrulline','czinc','carnitine','milga'];
const wa=message=>`https://wa.me/250792294432?text=${encodeURIComponent(message)}`;
function WhatsAppIcon(){return <svg width="21" height="21" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><path d="M20.5 11.7a8.5 8.5 0 0 1-12.8 7.4L3 20.5l1.4-4.6A8.5 8.5 0 1 1 20.5 11.7Z"/><path d="M8.5 7.5c-.8.1-1.1 1-.8 2 .8 2.7 2.8 4.7 5.6 5.5 1 .3 2-.1 2.2-.9l.2-.8-2.5-1.2-.8.9c-1.5-.7-2.5-1.7-3.1-3.1l.8-.8-1-2.2Z"/></svg>}
function Brand(){return <a className="brand" href="/#home" aria-label="MGREFOTS"><img className="brand-symbol" src="/brand/mark.png" width="240" height="194" alt=""/><span className="brand-wordmark"><strong>M.G.REFOTS<sup>®</sup></strong><small>DIETARY SUPPLEMENTS</small></span></a>}
function LanguagePicker({lang,setLang,t}){return <label className="language-picker"><Globe2 size={17}/><span className="sr-only">{t.language}</span><select aria-label={t.language} value={lang} onChange={e=>setLang(e.target.value)}><option value="en">English</option><option value="rw">Kinyarwanda</option><option value="ar">العربية</option></select></label>}
function OrderButton({className='',t}){return <a className={`btn btn-gold ${className}`} href={wa(t.request)} target="_blank" rel="noreferrer"><WhatsAppIcon/><span>{t.order}</span><ArrowRight size={16}/></a>}
export default function App(){
 const [lang,setLang]=useState(()=>{try{return ['en','rw','ar'].includes(localStorage.getItem('mgrefots-language'))?localStorage.getItem('mgrefots-language'):'en'}catch{return 'en'}});
 const [menu,setMenu]=useState(false); const initialProduct=new URLSearchParams(window.location.search).get('product'); const [cart,setCart]=useState(()=>Object.fromEntries(images.map(id=>[id,{selected:id===(images.includes(initialProduct)?initialProduct:'creatine'),quantity:id===(images.includes(initialProduct)?initialProduct:'creatine')?1:0}]))); const [submitting,setSubmitting]=useState(false); const [notice,setNotice]=useState(''); const [sent,setSent]=useState(false); const [form,setForm]=useState({name:'',phone:'',city:'',area:'',street:''}); const t=copy[lang];
 useEffect(()=>{document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';try{localStorage.setItem('mgrefots-language',lang)}catch{}},[lang]);
 const order=(i)=>`${t.request} ${t.names[i]} (${t.specs[i]}).`;
 const icons=[Leaf,Truck,ShieldCheck,Dumbbell];
 const isOrderPage=window.location.pathname.replace(/\/$/,'')==='/order';
 const selectedItems=images.filter(id=>cart[id]?.selected).map(id=>({product:id,quantity:Number(cart[id].quantity)||1})); const orderTotal=selectedItems.reduce((sum,item)=>sum+t.prices[images.indexOf(item.product)]*item.quantity,0);
 useEffect(() => {
   const cleanup = installClickTracking();
   if (isOrderPage) trackEvent('begin_checkout', ecommerce(selectedItems));
   return cleanup;
 }, []);
 const updateCart=(id,updates)=>setCart(current=>({...current,[id]:{...current[id],...updates}}));
 const submitOrder=async event=>{event.preventDefault();if(!selectedItems.length){setNotice(t.selectAtLeastOne);return}setNotice('');setSubmitting(true);try{const response=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,items:selectedItems,website:''})});const data=await response.json();if(!response.ok)throw new Error(data.code==='ORDER_EMAIL_NOT_CONFIGURED'?t.emailNotReady:t.orderError);trackOrderResult(data,selectedItems);setSent(true);setNotice(t.orderSuccess)}catch(error){setNotice(error.message||t.orderError)}finally{setSubmitting(false)}};
 if(isOrderPage)return <div className="site-shell order-page"><header className="site-header"><div className="container header-inner"><Brand/><div className="header-controls"><LanguagePicker lang={lang} setLang={setLang} t={t}/><a className="order-back" href="/#shop">{t.backHome}</a></div></div></header><main className="order-main"><div className="order-card"><a href="/#home" className="order-brand"><Brand/></a><p className="section-kicker">MGREFOTS · KIGALI</p><h1>{t.orderTitle}</h1><p className="order-intro">{t.orderIntro}</p>{sent?<div className="order-success" role="status"><CheckCircle2 size={34}/><p>{notice}</p><a className="btn btn-gold" href="/#shop">{t.backHome}</a></div>:<form className="order-form" onSubmit={submitOrder}>
 <label>{t.fieldName}<input autoComplete="name" name="name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required maxLength="100"/></label>
 <label>{t.fieldPhone}<input type="tel" autoComplete="tel" name="phone" inputMode="tel" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} required maxLength="24" placeholder="+250 7xx xxx xxx" dir="ltr"/></label>
 <div className="order-address-grid"><label>{t.fieldCity}<input autoComplete="address-level2" name="city" value={form.city} onChange={e=>setForm({...form,city:e.target.value})} required maxLength="80"/></label><label>{t.fieldArea}<input autoComplete="address-level3" name="area" value={form.area} onChange={e=>setForm({...form,area:e.target.value})} required maxLength="100"/></label></div>
 <label>{t.fieldStreet}<input autoComplete="street-address" name="street" value={form.street} onChange={e=>setForm({...form,street:e.target.value})} required maxLength="160"/></label>
 <fieldset className="order-products"><legend>{t.fieldProduct}</legend>{images.map((id,i)=><div className={`order-product-row ${cart[id].selected?'selected':''}`} key={id}><label className="order-product-choice"><input type="checkbox" checked={cart[id].selected} onChange={e=>updateCart(id,{selected:e.target.checked,quantity:e.target.checked?Math.max(1,cart[id].quantity):0})}/><span><strong>{t.names[i]}</strong><small>{t.prices[i].toLocaleString('en-US')} RWF {t.perBottle}</small></span></label><label className="order-qty-control"><span>{t.fieldQty}</span><input type="number" aria-label={`${t.fieldQty}: ${t.names[i]}`} min="1" max="99" step="1" value={cart[id].selected?Math.max(1,cart[id].quantity):''} placeholder="0" disabled={!cart[id].selected} onChange={e=>updateCart(id,{quantity:Math.max(1,Math.min(99,Number(e.target.value)||1))})}/></label></div>)}</fieldset>
 <div className="order-total"><span>{t.total}</span><strong>{orderTotal.toLocaleString('en-US')} RWF</strong></div><p className="payment-note">{t.paymentNote}</p><input className="order-honeypot" type="text" name="website" tabIndex="-1" autoComplete="off" aria-hidden="true"/><button className="btn btn-gold order-submit" type="submit" disabled={submitting}>{submitting?t.submitting:t.submit}<ArrowRight size={17}/></button>{notice&&<p className="order-error" role="alert">{notice}</p>}</form>}<a className="order-whatsapp" href={wa(t.request)} target="_blank" rel="noreferrer"><WhatsAppIcon/>{t.order}</a></div></main><footer className="site-footer"><div className="container footer-inner"><Brand/><p>© {new Date().getFullYear()} MGREFOTS LTD. {t.rights}</p></div></footer></div>;
 return <div className="site-shell"><header className="site-header"><div className="container header-inner"><Brand/><nav className={`main-nav ${menu?'open':''}`} aria-label={t.nav[0]}>{['home','shop','about','contact'].map((id,i)=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)}>{t.nav[i]}</a>)}<a className="order-nav-link" href="/order">{t.orderNav}</a><OrderButton className="nav-whatsapp" t={t}/></nav><div className="header-controls"><LanguagePicker lang={lang} setLang={setLang} t={t}/><button className="menu-toggle" aria-expanded={menu} aria-label={menu?t.close:t.open} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></div></header>
 <main><section id="home" className="hero"><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow">{t.eyebrow}</p><h1>{t.title.map(line=><span key={line}>{line}</span>)}</h1><p className="hero-text">{t.intro}</p><div className="hero-actions"><a className="btn btn-gold" href="#shop">{t.shop}<ArrowRight size={18}/></a><a className="btn btn-outline" href={wa(t.request)} target="_blank" rel="noreferrer"><WhatsAppIcon/>{t.order}</a></div><div className="hero-mini-features">{[ShieldCheck,Truck,Dumbbell].map((Icon,i)=><div key={i}><Icon size={24}/><span>{t.mini[i]}</span></div>)}</div></div><div className="hero-visual"><img className="hero-scene" src="/brand/hero-products.webp" alt={t.names.slice(0,3).join(', ')} fetchPriority="high"/></div></div></section>
 <section className="benefit-strip"><div className="container benefit-grid">{icons.map((Icon,i)=><article key={i}><span className="benefit-icon"><Icon size={32} strokeWidth={1.8}/></span><div><strong>{t.benefits[i]}</strong><span>{t.benefitText[i]}</span></div></article>)}</div></section>
 <section id="shop" className="products-section section"><div className="container"><div className="section-heading"><h2>{t.featured}</h2><a href={wa(t.listRequest)} target="_blank" rel="noreferrer">{t.all}<ArrowRight size={16}/></a></div><div className="product-grid">{images.map((img,i)=><article className="product-card" key={img}><div className="product-image-wrap"><img src={`/products/${img}.webp`} alt={t.names[i]} loading="lazy" width="1000" height="1000"/></div><div className="product-card-copy"><h3>{t.names[i]}</h3><p className="product-subtitle">{t.specs[i]}</p><p>{t.descriptions[i]}</p><p className="product-price">{t.prices[i].toLocaleString('en-US')} RWF</p></div><a className="shop-now" href={`/order?product=${img}`}>{t.shopNow}<ArrowRight size={16}/></a></article>)}</div></div></section>
 <section className="delivery-band"><div className="delivery-photo" aria-hidden="true"/><div className="container delivery-inner"><div className="delivery-title"><MapPin size={34}/><div><strong>{t.delivery}</strong><p>{t.deliveryText}</p></div></div><OrderButton t={t}/><div className="delivery-points">{[PackageCheck,Bike,ShieldCheck].map((Icon,i)=><span key={i}><Icon size={28}/>{t.points[i]}</span>)}</div></div></section>
 <section id="about" className="section"><div className="container about-panel"><div><p className="section-kicker">{t.about}</p><h2>{t.aboutTitle}</h2><p>{t.aboutText}</p></div><div className="about-badges">{t.badges.map(text=><span key={text}><CheckCircle2 size={22}/>{text}</span>)}</div></div></section>
 <section id="contact" className="contact-section"><div className="container contact-grid"><div><h2>{t.contact}</h2><p>{t.contactText}</p><OrderButton t={t}/></div><div className="contact-card"><a dir="ltr" href="tel:+250792294432"><Phone size={21}/>+250 792 294 432</a><a dir="ltr" href="mailto:info@mgrefots.com"><Mail size={21}/>info@mgrefots.com</a><span><MapPin size={21}/>Kigali View Hotel, Nyamirambo</span><div className="social-row"><a href="https://www.instagram.com/mobadr2026/" aria-label="Instagram" target="_blank" rel="noreferrer"><Instagram/></a><a href="https://www.facebook.com/profile.php?id=61580765596064" aria-label="Facebook" target="_blank" rel="noreferrer"><Facebook/></a></div></div></div></section></main><footer className="site-footer"><div className="container footer-inner"><Brand/><p>© {new Date().getFullYear()} MGREFOTS LTD. {t.rights}</p></div></footer></div>
}
