import React, { useEffect, useState } from 'react';
import { ArrowRight, Bike, Dumbbell, Facebook, Globe2, Instagram, Leaf, Mail, MapPin, Menu, PackageCheck, Phone, ShieldCheck, Truck, X, CheckCircle2 } from 'lucide-react';
import { copy } from './storefront-copy';
import '@fontsource-variable/inter';
import '@fontsource-variable/noto-sans-arabic';
import '@fontsource/libre-baskerville/700.css';
const images=['creatine','citrulline','czinc','carnitine','milga'];
const wa=message=>`https://wa.me/250792294432?text=${encodeURIComponent(message)}`;
function WhatsAppIcon(){return <svg width="21" height="21" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><path d="M20.5 11.7a8.5 8.5 0 0 1-12.8 7.4L3 20.5l1.4-4.6A8.5 8.5 0 1 1 20.5 11.7Z"/><path d="M8.5 7.5c-.8.1-1.1 1-.8 2 .8 2.7 2.8 4.7 5.6 5.5 1 .3 2-.1 2.2-.9l.2-.8-2.5-1.2-.8.9c-1.5-.7-2.5-1.7-3.1-3.1l.8-.8-1-2.2Z"/></svg>}
function Brand(){return <a className="brand" href="#home" aria-label="MGREFOTS"><img className="brand-symbol" src="/brand/mark.png" width="240" height="194" alt=""/><span className="brand-wordmark"><strong>M.G.REFOTS<sup>®</sup></strong><small>DIETARY SUPPLEMENTS</small></span></a>}
export default function App(){
 const [lang,setLang]=useState(()=>{try{return ['en','rw','ar'].includes(localStorage.getItem('mgrefots-language'))?localStorage.getItem('mgrefots-language'):'en'}catch{return 'en'}});
 const [menu,setMenu]=useState(false); const t=copy[lang];
 useEffect(()=>{document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';try{localStorage.setItem('mgrefots-language',lang)}catch{}},[lang]);
 const order=(i)=>`${t.request} ${t.names[i]} (${t.specs[i]}).`;
 const OrderButton=({className=''})=><a className={`btn btn-gold ${className}`} href={wa(t.request)} target="_blank" rel="noreferrer"><WhatsAppIcon/><span>{t.order}</span><ArrowRight size={16}/></a>;
 const icons=[Leaf,Truck,ShieldCheck,Dumbbell];
 return <div className="site-shell"><header className="site-header"><div className="container header-inner"><Brand/><nav className={`main-nav ${menu?'open':''}`} aria-label={t.nav[0]}>{['home','shop','about','contact'].map((id,i)=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)}>{t.nav[i]}</a>)}<OrderButton className="nav-whatsapp"/></nav><div className="header-controls"><label className="language-picker"><Globe2 size={17}/><span className="sr-only">{t.language}</span><select aria-label={t.language} value={lang} onChange={e=>setLang(e.target.value)}><option value="en">English</option><option value="rw">Kinyarwanda</option><option value="ar">العربية</option></select></label><button className="menu-toggle" aria-expanded={menu} aria-label={menu?t.close:t.open} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></div></header>
 <main><section id="home" className="hero"><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow">{t.eyebrow}</p><h1>{t.title.map(line=><span key={line}>{line}</span>)}</h1><p className="hero-text">{t.intro}</p><div className="hero-actions"><a className="btn btn-gold" href="#shop">{t.shop}<ArrowRight size={18}/></a><a className="btn btn-outline" href={wa(t.request)} target="_blank" rel="noreferrer"><WhatsAppIcon/>{t.order}</a></div><div className="hero-mini-features">{[ShieldCheck,Truck,Dumbbell].map((Icon,i)=><div key={i}><Icon size={24}/><span>{t.mini[i]}</span></div>)}</div></div><div className="hero-visual"><img className="hero-scene" src="/brand/hero-products.webp" alt={t.names.slice(0,3).join(', ')} fetchPriority="high"/></div></div></section>
 <section className="benefit-strip"><div className="container benefit-grid">{icons.map((Icon,i)=><article key={i}><span className="benefit-icon"><Icon size={32} strokeWidth={1.8}/></span><div><strong>{t.benefits[i]}</strong><span>{t.benefitText[i]}</span></div></article>)}</div></section>
 <section id="shop" className="products-section section"><div className="container"><div className="section-heading"><h2>{t.featured}</h2><a href={wa(t.listRequest)} target="_blank" rel="noreferrer">{t.all}<ArrowRight size={16}/></a></div><div className="product-grid">{images.map((img,i)=><article className="product-card" key={img}><div className="product-image-wrap"><img src={`/products/${img}.webp`} alt={t.names[i]} loading="lazy" width="1000" height="1000"/></div><div className="product-card-copy"><h3>{t.names[i]}</h3><p className="product-subtitle">{t.specs[i]}</p><p>{t.descriptions[i]}</p></div><a className="shop-now" href={wa(order(i))} target="_blank" rel="noreferrer">{t.shopNow}<ArrowRight size={16}/></a></article>)}</div></div></section>
 <section className="delivery-band"><div className="delivery-photo" aria-hidden="true"/><div className="container delivery-inner"><div className="delivery-title"><MapPin size={34}/><div><strong>{t.delivery}</strong><p>{t.deliveryText}</p></div></div><OrderButton/><div className="delivery-points">{[PackageCheck,Bike,ShieldCheck].map((Icon,i)=><span key={i}><Icon size={28}/>{t.points[i]}</span>)}</div></div></section>
 <section id="about" className="section"><div className="container about-panel"><div><p className="section-kicker">{t.about}</p><h2>{t.aboutTitle}</h2><p>{t.aboutText}</p></div><div className="about-badges">{t.badges.map(text=><span key={text}><CheckCircle2 size={22}/>{text}</span>)}</div></div></section>
 <section id="contact" className="contact-section"><div className="container contact-grid"><div><h2>{t.contact}</h2><p>{t.contactText}</p><OrderButton/></div><div className="contact-card"><a dir="ltr" href="tel:+250792294432"><Phone size={21}/>+250 792 294 432</a><a dir="ltr" href="mailto:info@mgrefots.com"><Mail size={21}/>info@mgrefots.com</a><span><MapPin size={21}/>Kigali View Hotel, Nyamirambo</span><div className="social-row"><a href="https://www.instagram.com/mobadr2026/" aria-label="Instagram" target="_blank" rel="noreferrer"><Instagram/></a><a href="https://www.facebook.com/profile.php?id=61580765596064" aria-label="Facebook" target="_blank" rel="noreferrer"><Facebook/></a></div></div></div></section></main><footer className="site-footer"><div className="container footer-inner"><Brand/><p>© {new Date().getFullYear()} MGREFOTS LTD. {t.rights}</p></div></footer></div>
}
